exports_files(["run_command.sh"])

config_setting(
    name = "clang",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "clang",
    },
)

config_setting(
    name = "msvc",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "msvc",
    },
)

config_setting(
    name = "gcc",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "compiler",
    },
)


