pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#check-failure=0"
      - "label=ready-to-merge"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
