cc_binary(
    name = "caffeine",
    srcs = ["main.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//:caffeine",
        "@llvm//llvm:IRReader",
        "@llvm//llvm:Support",
    ],
)
