load("//bazel:bitcode.bzl", "bitcode_binary")

bitcode_binary(
    name = "maze",
    srcs = ["maze.c"],
)

bitcode_binary(
    name = "maze-symbolic",
    srcs = ["maze-symbolic.c"],
)

bitcode_binary(
    name = "demo",
    srcs = ["demo.c"],
)

bitcode_binary(
    name = "cpp_bench",
    srcs = ["cpp_bench.cpp"],
)

bitcode_binary(
    name = "digitcount",
    srcs = ["digitcount.c"],
)
