load("@//bazel:bitcode.bzl", "bitcode_library_standalone")

bitcode_library_standalone(
    name = "caffeine",
    hdrs = ["caffeine.h"],
    includes = ["/interface"],
    visibility = ["//visibility:public"]
)
