load("//third_party/capnp:capnproto.bzl", "capnp_library")

capnp_library(
    name = "caffeine-protos",
    srcs = glob(["*.capnp"]),
    include_prefix = "caffeine/Protos",
    visibility = ["//visibility:public"],
)
