load("//bazel:bitcode.bzl", "caffeine_bitcode_test")

caffeine_bitcode_test(
    name = "branch-false",
    srcs = ["branch-false.c"],
)

caffeine_bitcode_test(
    name = "branch-true",
    srcs = ["branch-true.c"],
)

caffeine_bitcode_test(
    name = "call-extern-function-ptr",
    srcs = ["call-extern-function-ptr.c"],
)

caffeine_bitcode_test(
    name = "cpp-vector",
    srcs = ["cpp-vector.cpp"],
)

caffeine_bitcode_test(
    name = "sdiv-negative",
    srcs = ["sdiv-negative.c"],
)

caffeine_bitcode_test(
    name = "sdiv-udiv-equal-nonnegative",
    srcs = ["sdiv-udiv-equal-nonnegative.c"],
)

caffeine_bitcode_test(
    name = "sext",
    srcs = ["sext.ll"],
)

caffeine_bitcode_test(
    name = "switch",
    srcs = ["switch.ll"],
)

caffeine_bitcode_test(
    name = "trunc",
    srcs = ["trunc.ll"],
)

caffeine_bitcode_test(
    name = "udiv-large",
    srcs = ["udiv-large.c"],
)

caffeine_bitcode_test(
    name = "zext",
    srcs = ["zext.ll"],
)
