name: bazel

on:
  # Don't build CI for stackbot internal branches, they are already built for PRs
  push:
    branches-ignore:
      - stackbot/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [opt]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk-cache
          key: bazel-${{ matrix.mode }}-${{ github.sha }}
          restore-keys: |
            bazel-${{ matrix.mode }}
      - name: Configure bazel flags
        shell: bash
        run: |
          echo build --compilation_mode=${{ matrix.mode }} >> .bazelrc
      - name: Logging build start time
        shell: bash
        run: |
          echo TIME_START=$(date +%s) >> $GITHUB_ENV
      - name: Build all caffeine targets
        run: bazel test //test/...
      - name: Logging build end time
        shell: bash
        run: |
          echo TIME_END=$(date +%s) >> $GITHUB_ENV
      - name: Prune unused build cache files
        shell: bash
        run: |
          export MINUTES=$(( (($TIME_END - $TIME_START) / 60) + 1 ))
          find ~/.cache/bazel-disk-cache -type f -amin +$MINUTES | xargs -r -- rm -f
