name: bazel

on:
  # Don't build CI for stackbot internal branches, they are already built for PRs
  push:
    branches-ignore:
      - stackbot/**
  pull_request:

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [opt, fastbuild]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/auth@v0
        id: 'auth'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure bazel flags
        shell: bash
        run: |
          echo > bazel/cache.bazelrc
          echo build --compilation_mode=${{ matrix.mode }}  >> local.bazelrc
          echo build --google_default_credentials           >> local.bazelrc
          echo build --remote_max_connections=1000          >> local.bazelrc
          echo build --local_cpu_resources=2                >> local.bazelrc
          echo build --jobs=96                              >> local.bazelrc
          echo build --remote_cache=https://storage.googleapis.com/swlynch-devenv-bazel-remote-cache >> local.bazelrc
      
      - name: Avoid uploading if we don't have credentials
        if: env.GOOGLE_CREDENTIALS == null
        shell: bash
        run: |
          echo build --remote_upload_local_results=false >> local.bazelrc

      - name: Build all caffeine targets
        run: bazelisk build -- //...

      - name: Run all tests
        run: |
          bazelisk test -- //... \
            $(bazelisk query 'kind(".*_test", //...) intersect attr("tags", "manual", //...)')

  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [fastbuild]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/auth@v0
        id: 'auth'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure bazel flags
        shell: bash
        run: |
          echo > bazel/cache.bazelrc
          echo build --compilation_mode=${{ matrix.mode }}  >> local.bazelrc
          echo build --google_default_credentials           >> local.bazelrc
          echo build --remote_max_connections=1000          >> local.bazelrc
          echo build --local_cpu_resources=2                >> local.bazelrc
          echo build --jobs=96                              >> local.bazelrc
          echo build --remote_cache=https://storage.googleapis.com/swlynch-devenv-bazel-remote-cache >> local.bazelrc
      
      - name: Avoid uploading if we don't have credentials
        if: env.GOOGLE_CREDENTIALS == null
        shell: bash
        run: |
          echo build --remote_upload_local_results=false >> local.bazelrc
      
      - name: Check formatting of all targets
        run: bazelisk run -- //:check-format

