name: bazel

on:
  # Don't build CI for stackbot internal branches, they are already built for PRs
  push:
    branches-ignore:
      - stackbot/**
  pull_request:

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [opt, fastbuild]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Find bazel output base
        id: bazel_info
        shell: bash
        run: |
          echo "::set-output name=output_base::$(bazel info output_base)"

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.bazel_info.outputs.output_base }}/external
          key: bazel-external-${{ hashFiles('WORKSPACE', 'third_party/*/*', 'bazel/dependencies.bzl') }}

      - uses: google-github-actions/auth@v0
        if: env.GOOGLE_CREDENTIALS != null
        id: 'auth'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure bazel flags
        shell: bash
        run: |
          echo > bazel/cache.bazelrc
          cat >> local.bazelrc <<- EOF
          build --compilation_mode=${{ matrix.mode }}
          build --remote_max_connections=1000
          build --local_cpu_resources=2
          build --jobs=256
          build --remote_cache=http://35.211.199.119
          EOF

      - name: Avoid uploading if we don't have credentials
        if: env.GOOGLE_CREDENTIALS == null
        shell: bash
        run: |
          echo build --remote_upload_local_results=false >> local.bazelrc

      - name: Pass google credentials
        if: env.GOOGLE_CREDENTIALS != null
        shell: bash
        run: |
          echo build --google_credentials=${{ env.GOOGLE_APPLICATION_CREDENTIALS }} >> local.bazelrc

      - name: Run all tests
        run: |
          bazelisk test -- //... \
            $(bazelisk query 'kind(".*_test", //...) intersect attr("tags", "manual", //...)')

  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [fastbuild]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
          
      - uses: google-github-actions/auth@v0
        if: env.GOOGLE_CREDENTIALS != null
        id: 'auth'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure bazel flags
        shell: bash
        run: |
          echo > bazel/cache.bazelrc
          cat >> local.bazelrc <<- EOF
          build --compilation_mode=${{ matrix.mode }}
          build --remote_max_connections=1000
          build --local_cpu_resources=2
          build --jobs=256
          build --remote_cache=http://35.211.199.119
          EOF

      - name: Avoid uploading if we don't have credentials
        if: env.GOOGLE_CREDENTIALS == null
        shell: bash
        run: |
          echo build --remote_upload_local_results=false >> local.bazelrc

      - name: Pass google credentials
        if: env.GOOGLE_CREDENTIALS != null
        shell: bash
        run: |
          echo build --google_credentials=${{ env.GOOGLE_APPLICATION_CREDENTIALS }} >> local.bazelrc

      - name: Check formatting of all targets
        run: bazelisk run -- //:check-format

