name: bazel

on:
  # Don't build CI for stackbot internal branches, they are already built for PRs
  push:
    branches-ignore:
      - stackbot/**
  pull_request:

env:
  BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [opt, fastbuild]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Find bazel output base
        id: bazel_info
        shell: bash
        run: |
          echo "::set-output name=output_base::$(bazel info output_base)"

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.bazel_info.outputs.output_base }}/external
          key: bazel-external-${{ hashFiles('WORKSPACE', 'third_party/*/*', 'bazel/dependencies.bzl') }}

      - name: Configure bazel flags
        shell: bash
        run: |
          echo > bazel/cache.bazelrc
          cat >> local.bazelrc <<- EOF
          build --compilation_mode=${{ matrix.mode }}
          build --remote_max_connections=1000
          build --local_cpu_resources=2
          build --jobs=256
          build --bes_backend=grpcs://cloud.buildbuddy.io
          build --remote_cache=grpcs://cloud.buildbuddy.io
          build --remote_timeout=3600
          build --bes_results_url=https://app.buildbuddy.io/invocation/
          EOF
      
      - name: Avoid uploading if we don't have credentials
        if: env.BUILDBUDDY_API_KEY == null
        shell: bash
        run: |
          echo build --remote_upload_local_results=false >> local.bazelrc

      - name: Specify azure authorization
        if: env.BUILDBUDDY_API_KEY != null
        shell: bash
        run: |
          echo build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }} >> local.bazelrc

      - name: Run all tests
        run: |
          bazelisk test -- //... \
            $(bazelisk query 'kind(".*_test", //...) intersect attr("tags", "manual", //...)')

  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [fastbuild]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Configure bazel flags
        shell: bash
        run: |
          echo > bazel/cache.bazelrc
          cat >> local.bazelrc <<- EOF
          build --compilation_mode=${{ matrix.mode }}
          build --remote_max_connections=1000
          build --local_cpu_resources=2
          build --jobs=256
          #build --bes_backend=grpcs://cloud.buildbuddy.io
          build --remote_cache=grpcs://cloud.buildbuddy.io
          build --remote_timeout=3600
          #build --bes_results_url=https://app.buildbuddy.io/invocation/
          EOF
      
      - name: Avoid uploading if we don't have credentials
        if: env.BUILDBUDDY_API_KEY == null
        shell: bash
        run: |
          echo build --remote_upload_local_results=false >> local.bazelrc

      - name: Specify buildbuddy api key
        if: env.BUILDBUDDY_API_KEY != null
        shell: bash
        run: |
          echo build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }} >> local.bazelrc
      
      - name: Check formatting of all targets
        run: bazelisk run -- //:check-format

