name: bazel

on:
  # Don't build CI for stackbot internal branches, they are already built for PRs
  push:
    branches-ignore:
      - stackbot/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [opt, fastbuild]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure bazel flags
        shell: bash
        run: |
          echo build --compilation_mode=${{ matrix.mode }}                    >> local.bazelrc
          echo build --bes_results_url=https://app.buildbuddy.io/invocation/  >> local.bazelrc
          echo build --bes_backend=grpcs://cloud.buildbuddy.io                >> local.bazelrc
          echo build --remote_cache=grpcs://cloud.buildbuddy.io               >> local.bazelrc
          echo build --remote_timeout=3600                                    >> local.bazelrc

      - name: Configure buildbuddy API token
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          echo build --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY >> local.bazelrc
      
      - name: Build all caffeine targets
        run: bazel build -- //... -//third_party/... //third_party/divine/...

      - name: Run all tests
        run: bazel test -- //test/unit

  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [fastbuild]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Configure bazel flags
        shell: bash
        run: |
          echo build --compilation_mode=${{ matrix.mode }}                    >> local.bazelrc
          echo build --bes_results_url=https://app.buildbuddy.io/invocation/  >> local.bazelrc
          echo build --bes_backend=grpcs://cloud.buildbuddy.io                >> local.bazelrc
          echo build --remote_cache=grpcs://cloud.buildbuddy.io               >> local.bazelrc
          echo build --remote_timeout=3600                                    >> local.bazelrc
          echo ${{ github.event_name }}

      - name: Configure buildbuddy API token
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          echo build --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY >> local.bazelrc
      
      - name: Check formatting of all targets
        run: bazel run -- //:check-format

