
name: build-and-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: insufficientlycaffeinated/bob
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure
        run: |
          mkdir -p build
          cmake -B build -DCAFFEINE_CI=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build "build" -j$(nproc)
      
      - name: Test
        run: |
          cd build
          ctest . --output-on-failure
