
name: build-and-test

on:
  # Don't build CI for stackbot internal branches, they are already built for PRs
  push:
    branches-ignore:
      - stackbot/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: insufficientlycaffeinated/bob
    strategy:
      matrix:
        compiler: [clang, gcc]
      # We explicitly want to run all the compilers
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure
        run: |
          . ./.github/scripts/setup-env.sh --compiler ${{ matrix.compiler }}
          mkdir -p build
          cmake -B build \
            -DCAFFEINE_CI=ON \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCAFFEINE_ENABLE_UBSAN=ON \
            -DCAFFEINE_ENABLE_LIBC=ON \
            -DCAFFEINE_ENABLE_ASAN=ON

      - name: Build
        run: cmake --build "build" -j$(nproc)

      - name: Test
        run: |
          cd build
          ctest . --output-on-failure -j$(nproc)
