
name: build-and-test

on:
  # Don't build CI for stackbot internal branches, they are already built for PRs
  push:
    branches-ignore:
      - stackbot/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: insufficientlycaffeinated/bob
    strategy:
      matrix:
        compiler: [clang, gcc]
      # We explicitly want to run all the compilers
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure
        run: |
          . ./.github/scripts/setup-env.sh --compiler ${{ matrix.compiler }}
          mkdir -p build
          cmake -B build \
            -DCAFFEINE_CI=ON \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCAFFEINE_ENABLE_UBSAN=ON \
            -DCAFFEINE_ENABLE_LIBC=ON \
            -DCAFFEINE_ENABLE_ASAN=ON

      - name: Build
        run: cmake --build "build" -j$(nproc)

      - name: Test
        run: |
          cd build
          ctest . --output-on-failure -j$(nproc)

      - name: Coverage
        if: ${{ matrix.compiler == 'clang' }}
        env:
          LLVM_PROFILE_FILE: "default.%p.profraw"
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          llvm-profdata-11 merge -sparse `find . -name "*.profraw"` -o default.profdata
          llvm-cov-11 show -instr-profile ./default.profdata bin/caffeine-unittest -format=text > coverage.txt
          bash <(curl -s https://codecov.io/bash)
