name: build-apt

on:
  # Don't build CI for stackbot internal branches, they are already built for PRs
  push:
    branches-ignore:
      - stackbot/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang, gcc]
      # We explicitly want to run all the compilers
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install required dependencies
        # ubuntu-latest already has many of the packages we want installed. See
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
        run: |
          sudo apt-get install -y \
            ninja-build \
            libgtest-dev \
            libfmt-dev \
            libboost-all-dev \
            capnproto libcapnp-dev \
            ccache
          sudo ./.github/scripts/update-alternatives-llvm.sh 11 20
          go get github.com/SRI-CSL/gllvm/cmd/...

      - name: Set up compiler env vars
        run: |
          ./.github/scripts/setup-env.sh --compiler ${{ matrix.compiler }}
          ./.github/scripts/setup-ccache.sh

      - name: Export Cache Timestamp
        id: ccache-cache-timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - uses: actions/cache@v2
        env:
          cache-name: cache-ccache
          cache-key-base: cache-ccache-${{ runner.os }}-${{ matrix.compiler }}
        with:
          path: .ccache
          key: ${{ env.cache-key-base }}-${{ steps.ccache-cache-timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ env.cache-key-base }}-

      # Note: We set CMP0116 to OLD to silence warnings that don't apply since
      #       we keep the policy as OLD anyway.
      - name: Configure
        run: |
          mkdir -p build
          cmake -B build -S . -G Ninja \
            -DCMAKE_POLICY_WARNING_CMP0116=OLD \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCAFFEINE_CI=ON \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCAFFEINE_ENABLE_UBSAN=ON \
            -DCAFFEINE_ENABLE_ASAN=ON \
            -DCAFFEINE_ENABLE_LIBC=ON

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd build
          ctest . --output-on-failure -j$(nproc)
