name: test-clang-format

on: pull_request

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: DoozyX/clang-format-lint-action@v0.10
          with:
            source: '.'
            clangFormatVersion: 9
