
name: coverage

on:
  # Don't build CI for stackbot internal branches, they are already built for PRs
  push:
    branches-ignore:
      - stackbot/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: insufficientlycaffeinated/bob
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Envars
        run: |
          ./.github/scripts/setup-env.sh --compiler clang

      - name: Configure
        run: |
          echo $CXX
          mkdir -p build
          cmake -B build \
            -DCAFFEINE_CI=ON \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCAFFEINE_ENABLE_UBSAN=ON \
            -DCAFFEINE_ENABLE_LIBC=ON \
            -DCAFFEINE_ENABLE_ASAN=ON \
            -DCAFFEINE_ENABLE_COVERAGE=ON \
            -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build "build" -j$(nproc)

      - name: Test
        run: |
          cd build
          ctest . --output-on-failure -j$(nproc)

      - name: Coverage
        env:
          LLVM_PROFILE_FILE: "default.%p.profraw"
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cd build
          find . -name "*.profraw"
          llvm-profdata-11 merge -sparse `find . -name "*.profraw"` -o default.profdata
          llvm-cov-11 show -instr-profile ./default.profdata bin/caffeine-unittest -format=text > coverage.txt
          bash <(curl -s https://codecov.io/bash)
